SportsApplication/Models/Result.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Sports_Application.Models
{
    public class Result
    {
        public int Id { get; set; }
        [Required]
        public int TestId { get; set; }
        [Display(Name ="Name")]
        [Required]
        public string UserId { get; set; }
        [Display(Name = "Distance")]
        [Required]
        public int Data { get; set; }
    }
}

SportsApplication/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sports_Application.Models;
using SportsApplication.Models;

namespace SportsApplication.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ResultController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public ResultController(IData data,IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        [HttpGet("{TestId:int}")]
        [Route("editTest/{TestId}")]
        public object ViewResult(int TestId)
        {

            var test = unitOfWork.Data.GetTestByid(TestId);
            ViewResultModel obj = new ViewResultModel
            {
                Date = test.Date,
                TestType = test.TestType,
                TestId = TestId,
                AtheleteNames = unitOfWork.Data.GetAtheleteNamesWithDataByTestId(TestId)
            };
            return Ok(obj);
        }
       
        [HttpGet]
        [Route("addAthelete/{id}")]
        public async Task<object> CreateResult(int TestId)
        {
            var resultmodel = new CreateResultModel
            {
                TestId = TestId,
                AtheleteList = await unitOfWork.Data.GetAllAtheleteList()
            };
            return Ok(resultmodel);
        }

        [HttpPost]
        [Route("addAthelete")]
        public async Task<object> CreateResult(CreateResultModel resultmodel)
        {
            Result result = new Result
            {
                
                Id = resultmodel.Id,
                TestId = resultmodel.TestId,
                Data = resultmodel.Data,
                UserId = resultmodel.UserId
            };
            resultmodel.AtheleteList = await unitOfWork.Data.GetAllAtheleteList();
            int status = unitOfWork.Data.AddResult(result);
            if(status==0)
            {
                 return Ok(new { status});
            }
            else
            {

                unitOfWork.Data.IncrementCountByTestId(resultmodel.TestId);
                unitOfWork.Commit();
                //"ViewResult", "Result", new { testid = resultmodel.TestId }
                return Ok(new { status });
            }
            
        }

        [HttpGet("{Id:int}")]
        [Route("editResult/{Id}")]
        public async Task<object> EditResult(int Id)
        {
            var result = unitOfWork.Data.GetResultById(Id);
            var atheletes = unitOfWork.Data.GetAtheleteNamesWithDataByTestId(result.TestId);
            CreateResultModel ResultModel = new CreateResultModel
            {
                TestId = result.TestId,
                UserId = result.UserId,
                Data = result.Data,
                Id = result.Id,
                AtheleteList = await unitOfWork.Data.GetAllAtheleteList()
            };
            return Ok(ResultModel);
        }

        [HttpPost]
        [Route("updateResult")]
        public async Task<object> EditResult(CreateResultModel resultmodel)
        {
            resultmodel.AtheleteList = await unitOfWork.Data.GetAllAtheleteList();
            Result result = new Result
            {

                Id = resultmodel.Id,
                TestId = resultmodel.TestId,
                Data = resultmodel.Data,
                UserId = resultmodel.UserId
            };
            
            int status = unitOfWork.Data.Update(result);
            if (status == 0)
            {
                ViewBag.message = "Athelete already exists";
                return Ok(new { status });
            }
            else
            {
                unitOfWork.Commit();
                return Ok(new { status });
            }
        }

        [HttpDelete]
        [Route("deleteResult/{Id}/{TestId}")]
        public Object DeleteResult(int Id,int TestId)
        {
            unitOfWork.Data.DeleteTestResultById(Id);
            unitOfWork.Data.DecrementCountByTestId(TestId);
            unitOfWork.Commit();
            return Ok();
        }
        [Authorize(Roles = "Coach")]
        public IActionResult ConfirmDeleteResult(int Id)
        {
            return View(unitOfWork.Data.GetResultById(Id));
        }
    }
}

SportsApplication/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Sports_Application.Models;
using SportsApplication.Models;

namespace SportsApplication.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TestController : Controller
    {

        private readonly IUnitOfWork unitOfWork;

        public TestController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        [Authorize(Roles = "Coach")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Coach")]
        public async Task<IActionResult> CreateTest()
        {
            Test test = new Test();
            var user = await unitOfWork.Data.GetUserAsync(HttpContext.User);
            test.CoachId = user.Id;
            return View(test);
        }

        [HttpPost]
        [Authorize]
        [Route("createTest")]
        public IActionResult CreateTest(Test test)
        {

            unitOfWork.Data.AddTest(test);
            unitOfWork.Commit();
            return Ok(new { test }); 
            
            
        }

        //[Authorize(Roles = "Coach")]
        [Route("deleteTest/{Id}")]
        public object DeleteTest(int Id)
        {
            unitOfWork.Data.DeleteTestByTestid(Id);
            unitOfWork.Commit();
            return Ok();
        }

        [Authorize(Roles = "Coach")]
        public IActionResult ConfirmDeleteTest(int Id)
        {  
            return View(unitOfWork.Data.GetTestByid(Id));
        }
    }
}

SportsApplication/Views/Result/ConfirmDeleteResult.cshtml
@{
    ViewData["Title"] = "Confirm";
}

@model Sports_Application.Models.Result

<h1>Confirm</h1>
<div>
    <p>Do you want to delete this athelete from this test?</p>
</div>
<a class="btn btn-danger" asp-controller="Result" asp-action="DeleteResult" asp-route-Id="@Model.Id" asp-route-TestId="@Model.TestId">Yes</a>
<a class="btn btn-primary" asp-controller="Result" asp-action="ViewResult" asp-route-TestId="@Model.TestId">No</a>

SportsApplication/Views/Result/CreateResult.cshtml
@{
    ViewData["Title"] = "ADD NEW ATHELETE";
}

@model SportsApplication.Models.CreateResultModel

<form method="post">
    <div class="form-signin">
        <h2 class="form-signin-heading">ADD NEW ATHELETE TO TEST</h2>
        <div class="form-group">
            <input type="hidden" asp-for="@Model.TestId" class="form-control" />

            <label asp-for="@Model.UserId"></label>
            <select asp-for="@Model.UserId" class="form-control">
                <option value="-1" selected disabled>Choose</option>
                @foreach (var item in Model.AtheleteList)
                {

                    <option value="@item.id">@item.name</option>
                }
            </select>
            <span asp-validation-for="@Model.UserId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Data"></label>
        <input type="number" asp-for="@Model.Data" class="form-control" />
        <span class="text-danger" asp-validation-for="@Model.Data"></span>
    </div>
    <button type="submit" class="btn btn-primary" asp-route-Test=@Model>Save</button>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

@if (@ViewBag.message != null)
{
    <div class="alert alert-info">@ViewBag.message</div>
}

SportsApplication/Views/Result/EditResult.cshtml
@{
    ViewData["Title"] = "Edit Athelete";
}

@model SportsApplication.Models.CreateResultModel

<form method="post">
    <div class="form-signin">
        <h2 class="form-signin-heading">CHANGE DATA FOR ATHELETE</h2>
        <div class="form-group">
            <input type="hidden" asp-for="@Model.Id" class="form-control" />
            <input type="hidden" asp-for="@Model.TestId" class="form-control" />
            <label asp-for="@Model.UserId" class="control-label"></label>
            <select asp-for="@Model.UserId" class="form-control">
                <option value="-1" selected disabled>Choose</option>
                @foreach (var item in Model.AtheleteList)
                {

                    <option value="@item.id">@item.name</option>
                }
            </select>
            <span asp-validation-for="@Model.UserId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Data"></label>
        <input type="number" asp-for="@Model.Data" class="form-control" />
        <span class="text-danger" asp-validation-for="@Model.Data"></span>
    </div>
    <button type="submit" class="btn btn-primary" asp-route-Test="@Model">Save Test</button>
</form>
<br />
<a class="btn btn-danger" asp-controller="Result" asp-action="ConfirmDeleteResult" asp-route-id="@Model.Id">Delete athelete</a>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

@if (@ViewBag.message != null)
{
    <div class="alert alert-info">@ViewBag.message</div>
}

SportsApplication/Views/Result/ViewResult.cshtml
@{
    ViewData["Title"] = "All Tests";
}

@model SportsApplication.Models.ViewResultModel

<h1>@Model.TestType Dt.@Model.Date.ToShortDateString()</h1>

<input type="hidden" asp-for="@Model.TestId" />

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Distace<br />(meter)</th>
            <th>Fitness<br />Rating</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < @Model.AtheleteNames.Count(); i++)
        {
            <tr>
                <td><a asp-controller="Result" asp-action="EditResult" asp-route-Id="@Model.AtheleteNames.ElementAt(i).Id">@(i + 1). @Model.AtheleteNames.ElementAt(i).Name</a></td>
                <td>@Model.AtheleteNames.ElementAt(i).Data</td>
                <td>@Model.AtheleteNames.ElementAt(i).FitnessRanking</td>
            </tr>
        }
    </tbody>
</table>


<a class="btn btn-primary" asp-controller="Result" asp-action="CreateResult" asp-route-TestId="@Model.TestId">Add New Athelete To Test</a>
<br/>
<br />
<a class="btn btn-danger" asp-controller="Test" asp-action="ConfirmDeleteTest" asp-route-Id="@Model.TestId">Delete Test</a>